In [45]:
import numpy as np

In [46]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [47]:
X=np.array([[1,2,3],[4,5,6]])
print(X)
W1=np.array([[1,2,3,4],[2,3,4,5],[3,4,5,6]])
W2=np.array([[1,2],[2,3],[4,5],[5,6]])
b1=np.array([2,3,4,5])
b2=np.array([4,3])

[[1 2 3]
 [4 5 6]]


In [48]:
h=np.dot(X,W1)+b1
h

array([[16, 23, 30, 37],
       [34, 50, 66, 82]])

In [49]:
a=sigmoid(h)
a

array([[0.99999989, 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        ]])

In [50]:
Y=np.dot(a,W2)+b2
Y

array([[15.99999989, 18.99999977],
       [16.        , 19.        ]])

---
実装



In [51]:
import numpy as np
class Sigmoid:
    def __init__(self):
        self.params =[]

    def forward(self,x):
        return 1/(1+np.exp(-x))
    

    